### ISSUE TITLE
redefinition of '_rv_bext' in gcc/config/riscv/rvintrin.h

### ISSUE THREAD

**Issue by fanghuaqi** [pz9115/riscv-gcc#23]
This lines are not matching this PR https://github.com/riscv/riscv-bitmanip/pull/102

https://github.com/pz9115/riscv-gcc/blob/riscv-gcc-experimental-v/gcc/config/riscv/rvintrin.h#L169-L180

It will cause this issue when using rvintrin.h

```
include/rvintrin.h:819:20: error: redefinition of '_rv_bext'
  819 | static inline long _rv_bext   (long rs1, long rs2) { return _rv32_bext   (rs1, rs2); }
      |                    ^~~~~~~~
10.2.0/include/rvintrin.h:807:20: note: previous definition of '_rv_bext' was here
  807 | static inline long _rv_bext  (long rs1, long rs2) { return _rv32_bext  (rs1, rs2); }
      |                    ^~~~~~~~
```

**Comment by pz9115** [comment]
Fix with this commit, thanks!

https://github.com/pz9115/riscv-gcc/commit/c7cb371e2e219a788fba0341ca174128375a4dca

**Comment by fanghuaqi** [comment]
Thanks
