### ISSUE TITLE
关于编译RV64GCB 工具链失败的问题请教

### ISSUE THREAD

**Issue by qqjinger** [pz9115/riscv-gcc#24]
您好：

   我按照香山官方doc检出了对应版本的工具链。下图是香山官方docs\compiler\gnu_toolchain.md文件中检出工具链版本说明：
![image](https://user-images.githubusercontent.com/31501258/162899210-c21cb86c-d6db-4046-b317-bdd2fc1a1bfc.png)

下图则是我本地已检出版本的截图：
![image](https://user-images.githubusercontent.com/31501258/162899264-0c12adf4-8e16-455c-ad99-fd5f350cb918.png)

***
  但是，我按照官方的工具链编译方法编译时，出现了错误。
  下图是官方工具链编译方法：
![image](https://user-images.githubusercontent.com/31501258/162899322-5d1112ab-cde4-4264-8aa3-0ffa4a825d11.png)

不过我按照上述编译步骤进行编译时，报告了错误：
![image](https://user-images.githubusercontent.com/31501258/162899448-630e7c35-b0c9-4b7d-b09f-baf5e3b359a3.png)
![image](https://user-images.githubusercontent.com/31501258/162899476-eb9ee684-3110-4935-826b-89f9a98418c3.png)
我查看了libgcc/config.log文件，发现错误信息详情如下：
![image](https://user-images.githubusercontent.com/31501258/162899576-652a8b59-1118-43ed-9a35-4b93b39dc569.png)
![image](https://user-images.githubusercontent.com/31501258/162899630-f3241828-a924-40fb-bf2a-fb9c9fe3e513.png)

   请问有谁遇到过这个问题吗？谢谢

**Comment by pz9115** [comment]
本地验证没有发现同样的问题，我觉得可能是缺失了部分环境依赖，可以在安装这些依赖后再次尝试构建：
```
sudo apt-get install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev
```

**Comment by qqjinger** [comment]
您好：
本地环境已经确认有您所展示的依赖，如下：
![image](https://user-images.githubusercontent.com/31501258/163342341-626d98db-bcb1-426b-9195-f8a3e7c274db.png)
有个不一样的地方是：log中显示，注意，选中'libexpat1-dev' 而非 'libexpat-dev'。不知道这个是不是原因。

**Comment by pz9115** [comment]
我在这个issue中找到了和你遇到错误相同的情况，应该是bash环境有问题导致的，可以考虑检查一下机器的环境变量

https://github.com/riscv-collab/riscv-gnu-toolchain/issues/1

**Comment by qqjinger** [comment]
您好，我本地编译成功了，工具链版本如下：

- riscv toolchain版本回退到b715e4f01b43efef487166f75d5d85d3c33fa7ef；

- riscv-gcc 替换成软件所的版本 https://github.com/pz9115/riscv-gcc
切换到 riscv-gcc-experimental 分支 e5ec1231dd03ec1e10807ab5677a600489fa017e

- riscv-binutils 替换成软件所的版本 https://github.com/pz9115/riscv-binutils-gdb
切换到riscv-binutils-experimental 分支 520f5066004f7db320b39d09e9dd6d1a79202733

重要变化是，我根据编译错误信息，调整了工具链对应的指令集，修改后工具链编译命令如下：
```bash
cd riscv-gnu-toolchain
mkdir build
cd build
-  ../configure --prefix=PATH_TO_INSTALL --with-arch=rv64gc_zba_zbb_zbc_zbs
+  ../configure --prefix=PATH_TO_INSTALL --with-arch=rv64gc_zba_zbb_zbc
make linux -j
```

如此，编译没有问题。
不过有个问题，请问该riscv-gcc、riscv-binutils分支是不是不支持zbs扩展？

**Comment by pz9115** [comment]
该工具链是支持zbs扩展的

**Comment by qqjinger** [comment]
那就奇怪了，如果使用指令集rv64gc_zba_zbb_zbc_zbs，使用make linux -j编译时会报错，定位到错误信息是不支持zbs扩展，相关错误信息如下：
checking for riscv64-unknown-linux-gnu-gcc...  /riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/build/build-gcc-linux-stage1/./gcc/xgcc -B/riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/build/build-gcc-linux-stage1/./gcc/ -B/riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/compiled_rv64gcb_toolchain/riscv64-unknown-linux-gnu/bin/ -B/riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/compiled_rv64gcb_toolchain/riscv64-unknown-linux-gnu/lib/ -isystem /riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/compiled_rv64gcb_toolchain/riscv64-unknown-linux-gnu/include -isystem /riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/compiled_rv64gcb_toolchain/riscv64-unknown-linux-gnu/sys-include   
checking for suffix of object files... configure: error: in `/riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/build/build-gcc-linux-stage1/riscv64-unknown-linux-gnu/libgcc':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details
make[1]: *** [Makefile:11616??configure-target-libgcc] 错误1
make[1]: 离开目录/riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/build/build-gcc-linux-stage1??
make: *** [Makefile:370??stamps/build-gcc-linux-stage1] 错误 2

然后，我打开记录错误的log文件：/riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/build/build-gcc-linux-stage1/riscv64-unknown-linux-gnu/libgcc/config.log
发现如下错误信息：
configure:3565: $? = 1
configure:3778: checking for suffix of object files
configure:3800:  /riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/build/build-gcc-linux-stage1/./gcc/xgcc -B/riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/build/build-gcc-linux-stage1/./gcc/ -B/riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/compiled_rv64gcb_toolchain/riscv64-unknown-linux-gnu/bin/ -B/riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/compiled_rv64gcb_toolchain/riscv64-unknown-linux-gnu/lib/ -isystem /riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/compiled_rv64gcb_toolchain/riscv64-unknown-linux-gnu/include -isystem /riscv/liaoshujing/toolchain_gcc10.2_gcb/riscv-gnu-toolchain_newlyMaster_gccAndGdbPz9115/compiled_rv64gcb_toolchain/riscv64-unknown-linux-gnu/sys-include    -c -O2   -mcmodel=medlow  conftest.c >&5
Assembler messages:
Error: -march=rv64imafdc_zba_zbb_zbc_zbs: unknown z ISA extension `zbs'
configure:3804: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU C Runtime Library"
| #define PACKAGE_TARNAME "libgcc"
| #define PACKAGE_VERSION "1.0"
| #define PACKAGE_STRING "GNU C Runtime Library 1.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL "http://www.gnu.org/software/libgcc/"
| /* end confdefs.h.  */
上面说的正是不支持zbs扩展。

另外，请问该分支支持的B扩展，是0.92还是1.0标准的B扩展？

**Comment by pz9115** [comment]
我在本地再次尝试构建，使用带zbs的--with-arch参数还是通过的，我的仓库中B扩展是0.92版本的，最新1.0扩展的支持已经提交到了upstream, 你可尝试通过checkout到upstream的master分支构建后使用

git://gcc.gnu.org/git/gcc.git

git://sourceware.org/git/binutils-gdb.git

**Comment by qqjinger** [comment]
您好，能否分享下您本地riscv-gnu-toolchain、 riscv-gcc、riscv-binutils编译zbs成功的git分支和版本？谢谢

**Comment by pz9115** [comment]
toolchain分支：master  https://github.com/riscv/riscv-gnu-toolchain commit:  b715e4f01b43efef487166f75d5d85d3c33fa7ef

gcc分支：riscv-gcc-experimental https://github.com/pz9115/riscv-gcc.git commit: ba72b9fb037 Merge pull request #11 from WuSiYu/riscv-gcc-experiment

binutils分支：riscv-binutils-experimental https://github.com/pz9115/riscv-binutils-gdb.git commit: 981aefbe0cb94e1fb0ee6aa03e8fc6421bf6ddf6

**Comment by qqjinger** [comment]
我在本地尝试了，您给的两种分支版本，都能成功编译出zbs扩展指令，谢谢。

**Comment by qqjinger** [comment]
您好，另外我想请教下，怎么查看当前gcc编译器支持的指令集架构以及对应的版本，谢谢

**Comment by pz9115** [comment]
gcc支持的扩展定义在gcc/common/config/riscv/riscv-common.c文件中，不同分支对应的扩展可能不同，建议参考upstream中的扩展支持，比较全面:

https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/common/config/riscv/riscv-common.cc;h=1501242e2960e600b15e0866a78619aae27397e0;hb=HEAD#l112

https://github.com/pz9115/riscv-gcc/blob/ba72b9fb037a063f10cbaece3d73f56d48e11fcc/gcc/common/config/riscv/riscv-common.c#L90

格式为——{扩展名称，spec版本，主版本，次版本}

**Comment by qqjinger** [comment]
好的，很有帮助，非常感谢
