### ISSUE TITLE
Can't use zdinx imply zfinx like d imply f in gcc part in arch

### ISSUE THREAD

**Issue by pz9115** [pz9115/riscv-gcc#3]
We want to use zdinx imply zfinx like d imply f in gcc part，use riscv-gcc-10.2.0 releases as base branch

for example, you can compile with "--with-arch=rv64imadc" that equal to "--with-arch=rv64imafdc"

this will generate right arch args in .attribute part

===================================

.attribute arch, "rv64i2p0_m2p0_a2p0_f2p0_d2p0_c2p0"

===================================

We had added the z*inx imply info in [riscv-common.c](https://github.com/pz9115/riscv-gcc/blob/riscv-gcc-10.2.0-zfinx/gcc/common/config/riscv/riscv-common.c) and [multilib-generator](https://github.com/pz9115/riscv-gcc/blob/riscv-gcc-10.2.0-zfinx/gcc/config/riscv/multilib-generator)
but it only works in multilib-generator part, still can't generator right .attribute when only use arch zdinx

===================================

.attribute arch, "rv64i2p0_m2p0_a2p0_c2p0_zdinx2p0"

===================================

Maybe we miss add something or it has some problems.

**Comment by kito-cheng** [comment]
Hmmm, this bug is fixed on https://github.com/riscv/riscv-gcc/tree/riscv-gcc-10.2.0-bump by this commit https://github.com/riscv/riscv-gcc/commit/ec0ade559410ee242ca356928d718387f8bb68ec, could you try with this patch?

**Comment by pz9115** [comment]
Ok, I will try it.  thanks!

**Comment by pz9115** [comment]
This problem is fixed by Kito's patch, close.
